---
output:
  pdf_document: default
  html_document: default
---
# Pathway and Gene Ontology Enrichment

## Cytoscape and ClueGO

The ClueGO plugin of Cytoscape can run both **pathway enrichment** and **ontology enrichment** analysis. In other words, we can check which pathways and ontologies are overrepresented by our set of interesting genes (for example, differentially expressed genes or genes from interesting expression modules). Essentially, we are looking to see if any of those pathways and ontologies contain more genes of interest than we would expect if we had instead grabbed the same number of random genes to feed into the enrichment analysis.

Here we will use the KEGG (Kyoto Encyclopedia of Genes and Genomes) PATHWAY database (https://www.genome.jp/kegg/pathway.html) to look for enriched pathways. And we will use GO (gene ontology) ontologies (https://geneontology.org/) to look for enriched ontologies. Feel free to try other pathway and ontology options.

**KEGG PATHWAY**

Pathways for:  
+ Metabolism  
+ Genetic Information Processing  
+ Cellular Processes  
+ Organismal Systems  
+ Human Diseases  
+ Drug Development


**Gene Ontology**

Gene ontologies describe the function of genes in biological systems using a structured vocabulary that crosses species boundaries and that is both human-readable and machine-readable. Common gene ontology sets include:  
+ Biological Process  
+ Molecular Function  
+ Cellular Component


## Running ClueGO

As you found out, the mouse dataset is underpowered. It doesn't have enough differentially expressed genes to find significantly enriched pathways or ontologies.

We'll use differential expression results that I ran for you on the pneumonia study (see the Coexpression chapter). Then we'll try using the coexpression modules from the same study.

First, let's get the data. There are 209 genes whose expression is significantly higher (p≤0.01) in COVID-19 pneumonias compared to other pneumonias, and 528 whose expression is significantly lower.

1) Copy the file with differentially expressed genes (p<=0.01) onto your local computer using FileZilla (/home/data/diffexpr/covid_v_other_pneumonia.sig01.tsv).

2) Open it in excel or something similar and copy the gene names.

Now, let's run ClueGO.

1) Open the Cytoscape app, and load the ClueGO plug-in: Apps --> App Manager

2) Make sure the species is set to human (*Homo sapiens*)

3) Paste the genes into clueGO in the box under the species.

4) Under "Ontologies/Pathways", keep the "Biological Process" gene ontology and click the kegg pathways. Select different node shapes.

5) Click "Show Only Pathways with PV ≤" and put in 0.01.

6) Expand the "Statistical Options" menu. In the first box, change the selection from the default ("Enrichment/Depletion") to "Enrichment.

7) Click the “Use GO Term Fusion” box. It’s typically a good idea to check this box as it will improve runtime and simplify the results by eliminating redundancy.

8) Run the analysis by clicking start. It will take several minutes.

Look at the results.

1) When it’s finished, look to the bottom right of the screen. Select the "ClueGO Results (Cluster #1)" tab, and click the icon "Save ClueGO results tables" to your local computer

2) Open the new directory. Open the .png (not the overview) with GO terms represented with a horizontal bar graph as they are shown in the “Cluster #1” tab of in the software. Adjacent bars of the same color are terms that belong to the same group.

3) The most generally useful file is “NodeAttributeTables.txt”. Open it in excel or something similar. Filter the file for lines where "Overview Term" is "TRUE". This will cut down on the amount of data to look through. Both gene ontology and kegg pathways will show up in this file.

Go to https://www.genome.jp/kegg/ and take a look at one of the pathways.

<!--Sometimes the genes we found are listed as an alias on the KEGG pathway map. Sometimes they aren't found--maybe the pathway visuals haven't been updated?-->

## Additional options

Let's inspect some additional options.

Under "Advanced Term / Pathway Selection", The “GO Term/Pathway Selection” box will set the criterion for what is a qualifying GO term.

The “GO Term/Pathway Network Connectivity” scroll tab will set the kappa score threshold for what the edges that appear between nodes. Kappa score is a measure of relation any and all GO terms based on the number of associated genes they have in common. For more details regarding this calculation, click on the “?” icon.

Expand the “Grouping Options” box. Recall the variable (True/False) of the last column (Overview Term) in the node attribute table file we looked at. Those with a “True” value (as well as a check mark next to the GO id in the “Clue GO Results” tab in Cytoscape) are the leading term in the group, meaning it is the group with the lowest p-value.

The criterion to determine the leading term can be changed via the “Leading Group Term based on” selection. The threshold of commonality for what constitutes a group can also be adjusted, if so chosen.

## CluePedia

<!-- Need to figure this out a little better and how to see the log2FC colors work (need to show genes) -->

Select the "CluePedia" tab, and click the network icon. This will add miniature gene nodes within the edges between nodes. As of now, however, it is not apparent which of them are upregulated and which are downregulated.

Navigate to File –> Import –> Table from File, and select the document from which the gene list was originally input. In the new window, chose “To selected networks only”. Import data as "Node Table Columns". Under the “Key Column for Network” menu, pick “Input Gene ID”, then “OK”.

In the control panel, on the left side of Cytoscape, select ”Style”. Click the "+". For column, choose “Log2Fold change” and for mapping type, select “Continuous Mapping” and click the spectrum map.

In the window that appears, drag the handle position to 0 and change the color to grey or white. Then, drag the margins in to about a log2FoldChange of 2 and change their color. Change the arrows on the extremes to the same color.

You can save the session by clicking the icon at the top right of the app, which will allow you to return to the visualization and settings of the analysis in another session.

## Revigo

Revigo (reduce & visualize gene ontology) is a tool that will collapse related GO terms and create some interactive visualizations.

Copy your enriched GO terms ("ID" column) and the "Term PValue Corrected with Bonferroni step down" column (note: it is ok to include the KEGG pathways that are in the "ID" column, Revigo will just warn you that it can't find any matches for them and will ignore them).

Go to http://revigo.irb.hr/ and paste them in the box.

Change the species to "Homo sapiens".

Click on "Start Revigo".

After we explore the results, try rerunning it, changing "How large would you like the resulting list to be" to different values.

## geneontology.org

Go back to the covid_v_other_pneumonia.sig01.tsv file and copy the gene names. Run a gene ontology enrichment at https://geneontology.org/.

## Modules

Now run enrichment analyses on the green and turquoise modules, which were up and down regulated in COVID-19 pneumonias, respectively, compared to other peumonias. Earlier you generated linux files with the gene names ("green.txt" and "turquoise.txt")
